
spring:
  #************ H2  Begin ***************
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  #************ H2  End ****************

# 日志信息，默认输出控制台
# 日志级别：TRACE < DEBUG < INFO < WARN < ERROR < FATAL
logging:
  level:
    root: INFO
    com.supermap: DEBUG
    mybatis.mapper: TRACE
  file: ./logs/ops-log.log

# 开发时候可以配置为 true 以获取更多日志信息
debug: true

## 需要刻意暴露的配置项、是否加密
property:
  items:
    - name: server.port
      command: 服务的端口号
      encrypt: false
    - name: spring.profiles.active
      command: 测试环境配置为（dev）、生产环境配置为（product）
      encrypt: false
    - name: ops.work.bdck.database.url
      command: bdck的数据库ip与端口（如：127.0.0.1:1521）
      encrypt: true
    - name: ops.work.bdck.database.password
      command: bdck的数据库密码（如：password）
      encrypt: true


  ######## 一些默认的配置 ######
  # 开发、测试环境：master数据库（h2)数据源的url：jdbc:h2:file:./db/h2/database-dev
  # 生产环境：master数据库（h2)数据源的url：jdbc:h2:file:./db/h2/database-product
  # 密码：内部加密
  # master 数据库建库语句所在目录：db/master/migration

####### 其它一些无关的，可能会用到的 #######
  # 已经在配置中将 ctx 默认为全局变量
  # freemarker全局变量
  # spring:
  #  freemarker:
  #    request-context-attribute: ctx

  # master 数据源（ h2 数据库连接方式）
  # url有以下几种形式:
  # jdbc:h2:E:*/database 会持久化到磁盘文件，但是是单连接
  # jdbc:h2:tcp://IP/database 通过远程连接的方式，需要启动 h2 数据库
  # jdbc:h2:mem:database 直接在内存中，程序只要重启就会消失
  # jdbc-url: jdbc:h2:file:D:\Code\database
  # url: jdbc:h2:mem:h2test
  # datasource:
  #   master:
  #     url: jdbc:h2:file:./db/h2/database


# 和加密有关的测试
jasypt:
  test:
    encryptd1: lalalalala
    encryptd2: OPTENC(NKXN0vwQydF9p3ObWUw7iHUXXOvnz6gh)
    text: canyouseeme