server:
  port: 8081
# freemarker全局变量
# spring:
#  freemarker:
#    request-context-attribute: ctx

# 日志信息，默认输出控制台
# 日志级别：TRACE < DEBUG < INFO < WARN < ERROR < FATAL
logging:
  level:
    root: INFO
    com.supermap: DEBUG
    mybatis.mapper: TRACE
  file: ./logs/ops-log.log

# 开发时候可以配置为 true 以获取更多日志信息
debug: false

spring:
  datasource:
    ## master 数据源
    # url有以下几种形式:
    # jdbc:h2:E:*/database 会持久化到磁盘文件，但是是单连接
    # jdbc:h2:tcp://IP/database 通过远程连接的方式，需要启动 h2 数据库
    # jdbc:h2:mem:database 直接在内存中，程序只要重启就会消失
    master:
      #url: jdbc:h2:mem:h2test
      url: jdbc:h2:file:D:\Code\database
      #jdbc-url: jdbc:h2:file:D:\Code\database

  #************ H2  Begin ****************
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  #************ H2  End ****************
