## 生产环境的默认配置
## 更多全局配置，在代码中进行了硬编码，详见 com.supermap.config 包

spring:
  #************ H2  Begin ***************
  h2:
    console:
      enabled: true
      path: /h2-console
  #************ H2  End ****************

# 日志信息，默认输出控制台
# 日志级别：TRACE < DEBUG < INFO < WARN < ERROR < FATAL
logging:
  file: ./logs/ops-log.log

debug: false

## 需要刻意暴露的配置项、是否加密
property:
  items:
    - name: server.port
      command: 服务的端口号
    - name: spring.profiles.active
      command: 测试环境配置为（test）、生产环境配置为（product）
    - name: ops.work.bdck.database.url
      command: bdck的数据库ip、端口、实例（如：127.0.0.1:1521/orcl）
      encrypt: true
    - name: ops.work.bdck.database.password
      command: bdck的数据库密码（如：password）
      encrypt: true
