## 一些通用的配置

## 在生产环境初次执行时，将会自动生成的配置项，这些配置项对运维人员可见。
property:
  items:
    - name: server.port
      command: 服务的端口号
    - name: spring.profiles.active
      command: 测试环境配置为（test）、生产环境配置为（product）
    - name: ops.work.bdck.database.url
      command: bdck的数据库ip、端口、实例（如：127.0.0.1:1521/orcl）
      encrypt: true
    - name: ops.work.bdck.database.password
      command: bdck的数据库密码（如：password）
      encrypt: true
