server:
  port: 8081
# freemarker全局变量
# spring:
#  freemarker:
#    request-context-attribute: ctx

# 日志信息，默认输出控制台
# 日志级别：TRACE < DEBUG < INFO < WARN < ERROR < FATAL
logging:
  level:
    root: INFO
    com.supermap: DEBUG
    mybatis.mapper: TRACE
  file: ./logs/ops-log.log

# 开发时候可以配置为 true 以获取更多日志信息
debug: false

#************H2  Begin****************
spring:
  datasource:
    ## master 数据源
    master:
      #schema: classpath:db/schema-h2.sql
      #data: classpath:db/data-h2.sql
      jdbc-url: jdbc:h2:mem:h2test
      platform: h2
      username: sa
      password:
      driver-class-name: org.h2.Driver
  ## 自动装载 h2 数据库
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
#************H2  End****************

#************Mybatis  Begin****************
#mybatis:
#  type-aliases-package: com.supermap.entity
#  mapper-locations: classpath*:mapper/*.xml
#  check-config-location: true
#************Mybatis  End****************


