## 生产环境的默认配置
## 更多全局配置，在代码中进行了硬编码，详见 com.supermap.config 包

spring:
  #************ H2  Begin ***************
  h2:
    console:
      enabled: true
      path: /h2-console
  #************ H2  End ****************

# 日志信息，默认输出控制台
# 日志级别：TRACE < DEBUG < INFO < WARN < ERROR < FATAL
logging:
  file: ./logs/ops-log.log

debug: false

